### ISSUE TITLE
feat(verifier): Implement remaining channel functions

### ISSUE THREAD

**Issue by maxgillett** [ZeroSync/ZeroSync#40]
The following functions remain to be implemented in [`src/stark_verifier/channel.cairo`](https://github.com/ZeroSync/ZeroSync/blob/main/src/stark_verifier/channel.cairo):
- `read_queried_trace_states`
- `read_constraint_evaluations`

Both of these functions should authenticate the returned values against the trace/constraint commitment. For comparison, they are implemented in the Winterfell verifier here: [`verifier/src/channel.rs`](https://github.com/ZeroSync/winterfell/blob/main/verifier/src/channel.rs)

**Comment by RobinLinus** [comment]
Closed with a0099bc1aba9b0345f1ef644f9efeb893b5f3907, 4046cc4d6ec22ffc8f7de587c012179ef0c3bd2f, and bb13cb67e0d73f141d3086463ec944505eec9068.
