### ISSUE TITLE
feat(verifier): Combine evaluations of the DEEP composition polynomial

### ISSUE THREAD

**Issue by maxgillett** [ZeroSync/ZeroSync#41]
The following code remains to be implemented and tested:

https://github.com/ZeroSync/ZeroSync/blob/b92c1a3842c53cc9bb5529de29389d47789ea71b/src/stark_verifier/stark_verifier.cairo#L219-L236

The comparable Rust code can be found here: [verifier/src/composer.rs](https://github.com/ZeroSync/winterfell/blob/main/verifier/src/composer.rs)

**Comment by RobinLinus** [comment]
Completed with 6755a8b8605c514035d159cf7005d0487861de63.
