### ISSUE TITLE
Reorganize unit and integration tests into tests directory

### ISSUE THREAD

**Issue by maxgillett** [ZeroSync/ZeroSync#43]
We currently hold integration tests in the `tests` directory, but have unit tests living alongside source code in separate test-prefixed files.  This makes it difficult to locate unit tests, and bloats the source directory with code that's not needed to run the program. I'm in favor of moving all unit tests to a `tests/unit` subdirectory and moving integration tests to `tests/integration`. This is similar in organization to other Cairo projects like [kakarot](https://github.com/sayajin-labs/kakarot). Please share your thoughts.

**Comment by RobinLinus** [comment]
The idea behind the current directory structure was to make it easy to reuse our code by coping entire folders into other projects. Long-term plan was to split our code into git submodules. However, that was before we understood that we can use pip as package manager for our Cairo code. So now there's no reason anymore to bloat our source directory.

**Comment by RobinLinus** [comment]
Closed with 8fce076 .

**Comment by RobinLinus** [comment]
Closed with https://github.com/ZeroSync/ZeroSync/commit/8fce076c447300ff5205f0bf7b94440679052a30 .
