### ISSUE TITLE
fix(`fetch_transaction`): Wait for API answers and cache results for next run 

### ISSUE THREAD

**Issue by lucidLuckylee** [ZeroSync/ZeroSync#44]
Runs for blocks with 1000+ transactions fail due to a wrong merkle root calculated from the transactions fetched. Since blocks with less transactions do not fail, I suspect we reach the blockstream API call threshold.
- We should check error codes of the http requests in `fetch_transaction` in `src/transaction/transaction.cairo` and repeat the fetching process if it fails with a bit of delay. 
- For repeated test runs the fetched transactions should be cached and stored to be used in the next test run again.

These features can be implemented in the python hint in `fetch_transaction`.

**Comment by RobinLinus** [comment]
Maybe we can simply run our own Esplora server?

**Comment by lucidLuckylee** [comment]
Sure, but keep in mind that Hetzner doesn't allow running crypto clients on their servers. We would have to setup another server.

I also haven't investigated this issue and there might be a different problem with large blocks. But, if we throw an error on unexpected API answers we may rule it out as a cause.

**Comment by lucidLuckylee** [comment]
The API does not seem to block our requests but occasionally sends an error message back. I will change it so that upon receiving an error we try again after 30 secs.

SegWit blocks and txs  are another unrelated issue - the hashing for them is not implemented/activated yet and imo makes more sense to implement once we settled for a serilization method (read vs write).
