### ISSUE TITLE
dev: Build is broken

### ISSUE THREAD

**Issue by weex** [ZeroSync/ZeroSync#47]
As of commit [23c53f7](https://github.com/ZeroSync/ZeroSync/commit/23c53f756f6b7c35ac85887756c30854bafeae92) the CI fails.

Confirmed this with my own fork and a commit to trigger the action.
https://github.com/weex/ZeroSync/actions/runs/3919423933/jobs/6700422999

**Comment by lucidLuckylee** [comment]
Thank you for creating the issue!

We are aware and I traced this back to the tests in `tests/unit/stark_verifier/test_air.cairo` and `tests/unit/stark_verifier/test_composer.cairo`.
There is a file not found error in line 33 of `parser/src/lib.rs`. 

Can also reproduce it with a clean clone of the repo - so not limited to the ci. 
@RobinLinus do you know what could be wrong there?

**Comment by RobinLinus** [comment]
looks to me as if the unit test are run before the `fibonacci.bin` proof has been written to disk

**Comment by lucidLuckylee** [comment]
We need to call the setup that generates the fibonacci proof in each unit test suite beause protostar runs them on multiple cores and gets stuck if the `__setup__` step fails.

Fixed with [71d4276](https://github.com/ZeroSync/ZeroSync/commit/71d4276c469a7f031df0ea899162996e7a73f818).
