### ISSUE TITLE
feat: tool to generate program hash

### ISSUE THREAD

**Issue by lucidLuckylee** [ZeroSync/ZeroSync#60]
We currenty copy the program hash from the first failing chain_proof run and want a tool to generate it from a compiled cairo program (similar to cairo-hash-program from cairo-lang). The respective cairo code can be found in the `read_and_verify_stark_proof` function in  `src/stark_verifier/stark_verfier.cairo`. Note that it uses an already available proof and not the compiled program json.

**Comment by cryptskii** [comment]
```
import hashlib
from starkware.cairo.lang.compiler.cairo_compile import compile_cairo

def get_program_hash(cairo_code: str) -> str:
    """Generate program hash from Cairo code."""
    compiled = compile_cairo(cairo_code, "cairo_code")
    program = compiled.get('program')
    return hashlib.sha256(program).hexdigest()

if __name__ == "__main__":
    cairo_code = """
    main() -> (result) {
        ...
    }
    """
    program_hash = get_program_hash(cairo_code)
    print(f"Program hash: {program_hash}")

```

**Comment by cryptskii** [comment]
or

import json
import subprocess

def generate_program_hash(proof_file_path: str, program_hash_file_path: str):
    with open(proof_file_path) as f:
        proof = json.load(f)

    program = proof['program']
    program_json = json.dumps(program)

    cairo_hash_program = subprocess.Popen(['cairo-hash-program'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    program_hash, _ = cairo_hash_program.communicate(input=program_json.encode())
    program_hash = program_hash.decode().strip()

    with open(program_hash_file_path, 'w') as f:
        f.write(program_hash)

**Comment by cryptskii** [comment]
or

```use std::process::Command;
use std::fs::File;
use std::io::Write;

fn generate_program_hash(proof_file_path: &str, program_hash_file_path: &str) {
    let proof_file = File::open(proof_file_path).unwrap();
    let proof: serde_json::Value = serde_json::from_reader(proof_file).unwrap();
    let program = proof["program"].to_string();

    let cairo_hash_program = Command::new("cairo-hash-program")
        .stdin(program.as_bytes())
        .output()
        .expect("failed to execute cairo-hash-program");

    let program_hash = String::from_utf8_lossy(&cairo_hash_program.stdout).trim().to_string();

    let mut program_hash_file = File::create(program_hash_file_path).unwrap();
    program_hash_file.write_all(program_hash.as_bytes()).unwrap();
}
```
